"""Random doubles player.

Milestone 1 uses ``gen9randomdoublesbattle`` (random teams generated by
Showdown) as a stepping stone. The locked target format remains the current
official VGC regulation (see CLAUDE.md); switching to it requires a real
team file, which is milestone 1b.
"""

from __future__ import annotations

from poke_env.player import RandomPlayer
from poke_env.ps_client import AccountConfiguration, LocalhostServerConfiguration

DEFAULT_DOUBLES_FORMAT = "gen9randomdoublesbattle"


def make_random_doubles_player(
    username: str,
    battle_format: str = DEFAULT_DOUBLES_FORMAT,
) -> RandomPlayer:
    return RandomPlayer(
        account_configuration=AccountConfiguration(username, None),
        battle_format=battle_format,
        server_configuration=LocalhostServerConfiguration,
        log_level=30,
    )
